### ISSUE TITLE
Environmental setup

### ISSUE THREAD

**Issue by ghost** [kdmsit/crysmmnet#1]
Hi, thank you for sharing your great work.
I am trying to run your code on a virtual environment torch-1.13.1-cuda-11.6, but when I try to pip install requirements.txt, I have the following
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/croot/certifi_1671487769961/work/certifi'

I would appreciate any help.

Sincerely.

**Comment by kdmsit** [comment]
Again sorry for Late reply!!

This error is occurring due to cuda mismatch of your server and torch. Follow these steps -

Assuming Cuda version is 11.8

conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
conda install -c dglteam/label/cu118 dgl
pip install jarvis-tools==2022.9.16
pip install pytorch-ignite
pip install pandas
pip install transformers
pip3 install -U scikit-learn scipy matplotlib
pip install pydantic==1.8.1
